apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helm/python-helloworld
    repoURL: https://github.com/PeacePeters/SUSE-Cloud-Native-Foundations-Scholarship 
    targetRevision: HEAD
  # Sync policy
  syncPolicy:
    automated: {}
